services:

  # 3. Frontend (React + Vite)
  frontend:
    build:
      context: .
      args:
          FE_CONTAINER_PORT: ${FE_CONTAINER_PORT}
    container_name: ${FE_CONTAINER_NAME}
    image: ${FE_CONTAINER_NAME}        
    restart: on-failure
    # Elimino par no exponer el puerto
    # ports:
    #   - ${FE_CONTAINER_PORT}:${FE_CONTAINER_PORT} # Puerto para el frontend
    volumes:
      - .:/app
      - /app/node_modules
      # El frontend necesita saber dónde está el backend para los sockets
    env_file:
      - ../.env
    networks:
      transcendence_net:
        aliases:
          - frontend_alias
    depends_on:
      - ${BE_CONTAINER_NAME}

