apiVersion: 1
  # Configuración del datasource de PostgreSQL para Grafana 
datasources:
  # --- (POSTGRESQL) ---
    # Nombre del datasource en Grafana
  - name: Postgres_Transcendence
    # Tipo de base de datos
    type: postgres
    # url de conexión a la base de datos incluyendo host y puerto
    url: ${DB_HOST}:${DB_PORT}
    # Nombre de la base de datos    
    database: ${POSTGRES_DB}
    # Usuario de la base de datos
    user: ${POSTGRES_USER}    
    # Contraseña de la base de datos
    secureJsonData:
      password: ${POSTGRES_PASSWORD}

    uid: transcendence_001     
    # campos adicionales de configuración en formato JSON y almacenar en jsonData 
    jsonData:
      # Nombre de la base de datos
      database: ${POSTGRES_DB}
      # disable ssl para desarrollo local
      sslmode: 'disable'
      # 
      postgresVersion: 1600
      # postgresVersion: ${DB_VERSION}00      
      # When true, Grafana will create Time-series database built-in queries for PostgreSQL
      timescaledb: false
      # Parámetros personalizados de consulta
      #customQueryParameters: "options=-c datestyle=ISO,MDY"
  
  # --- (PROMETHEUS) ---
  - name: Prometheus
    type: prometheus
    # Aquí usamos el alias que definimos en el docker-compose de prometheus
    #url: http://prometheus_alias:9090
    url: http://prometheus:9090/prometheus 
    access: proxy
    isDefault: false
    uid: prometheus_001
    jsonData:
      # Intervalo de scrapeo por defecto
      timeInterval: "15s"

  # --- (GITHUB) ---
  - name: GitHub
    type: grafana-github-datasource
    uid: github_001
    access: proxy
    jsonData: {}
    # Aquí le pasamos el token de forma segura
    secureJsonData:
      accessToken: ${GITHUB_TOKEN}