services:

  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    container_name: ${GF_CONTAINER_NAME}
    user: "root"
    env_file:
      - ../.env
    environment:
      # - GF_SECURITY_ALLOW_EMBEDDING=${GF_SECURITY_ALLOW_EMBEDDING}
      # - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED}
      # - GF_AUTH_ANONYMOUS_ORG_NAME=${GF_AUTH_ANONYMOUS_ORG_NAME}
      - GF_SECURITY_ALLOW_EMBEDDING=true      # Permite incrustar en iframes
      - GF_AUTH_ANONYMOUS_ENABLED=true        # Permite ver sin login
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer     # Solo modo lectura
      - GF_INSTALL_PLUGINS=grafana-github-datasource  # Para github
      - GITHUB_TOKEN=${GITHUB_TOKEN} # Para github
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}  
      # - GF_SECURITY_COOKIE_SAMESITE=${GF_SECURITY_COOKIE_SAMESITE}
      # - GF_SECURITY_COOKIE_SECURE=${GF_SECURITY_COOKIE_SECURE}
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      # Para nginx
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=${GF_SERVER_SERVE_FROM_SUB_PATH}
    depends_on:
      - ${DB_CONTAINER_NAME}
    volumes:
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards/   
      # ALERTAS (Nueva línea)
      - ./provisioning/alerting:/etc/grafana/provisioning/alerting/
      - grafana_data:/var/lib/grafana
    # Elimino para no exponer el puerto
    # ports:
    #   - ${GF_CONTAINER_PORT}:${GF_SERVER_HTTP_PORT}
    networks:
      transcendence_net:
        aliases:
         - grafana_alias
    logging:
      driver: "json-file" # Use json-file for easier access if you need to debug raw logs
      options:
        max-size: "30k" # Keep each log file up to 30KB
        max-file: "3"   # Keep the 3 most recent log files 
