name: ${PROJECT_NAME}

include: # Please keep alphabetic order
  - adminer/docker-compose-adminer.yml
  - backend/docker-compose-backend.yml  
  - dbserver/docker-compose-dbserver.yml
  - frontend/docker-compose-frontend.yml
  - grafana/docker-compose-grafana.yml
  - prometheus/docker-compose-prometheus.yml
  - totp/docker-compose-totp.yml
  - nginx/docker-compose-nginx.yml

networks:
  public_net:         # <--- AÑADIDA: Red pública (Solo para Nginx)
    # name: public_net
    name: public_net_v2
    driver: bridge
  transcendence_net:
    name: thenet_v2
    driver: bridge
    # internal: true   # <--- Necesita salir al exterior para Oauth y Alerts
  auth_net:
    name: auth_net
    driver: bridge    
    internal: true # Aislada del mundo exterior
  db_net:
    name: db_net
    driver: bridge    
    internal: true # Aislada .Solo compartida con la base de datos

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/dbserver"
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: none
      device: "${TRANSCENDENCE_HOME}/data/grafana"
      o: bind
